CREATE TABLE IF NOT EXISTS {{ DATABASE }}.RAW.ORDERS (
  ORDER_ID      NUMBER        NOT NULL PRIMARY KEY,
  CUSTOMER_ID   NUMBER,
  ORDER_STATUS  VARCHAR(20),
  ORDER_AMOUNT  NUMBER(12,2),
  ORDER_TS      TIMESTAMP_NTZ,
  UPDATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS {{ DATABASE }}.CORE.ORDERS (
  ORDER_ID        NUMBER        NOT NULL PRIMARY KEY,
  CUSTOMER_ID     NUMBER,
  ORDER_STATUS    VARCHAR(20),
  ORDER_AMOUNT    NUMBER(12,2),
  ORDER_TS        TIMESTAMP_NTZ,
  SRC_UPDATED_AT  TIMESTAMP_NTZ,
  DW_INSERTED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  DW_UPDATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
