CREATE TABLE IF NOT EXISTS {{ DATABASE }}.AUDIT.PIPELINE_RUN_LOG (
  RUN_ID         NUMBER IDENTITY START 1 INCREMENT 1,
  PIPELINE       VARCHAR(100),
  STARTED_AT     TIMESTAMP_NTZ,
  FINISHED_AT    TIMESTAMP_NTZ,
  DURATION_MS    NUMBER,
  ROWS_INSERTED  NUMBER DEFAULT 0,
  ROWS_UPDATED   NUMBER DEFAULT 0,
  ROWS_DELETED   NUMBER DEFAULT 0,
  STATUS         VARCHAR(20),
  MESSAGE        VARCHAR(4000)
);
