-- Standard stream = full CDC (INSERT / UPDATE / DELETE) on the source table.
-- An UPDATE appears as a DELETE+INSERT pair with METADATA$ISUPDATE = TRUE.
CREATE STREAM IF NOT EXISTS {{ DATABASE }}.RAW.ORDERS_STREAM
  ON TABLE {{ DATABASE }}.RAW.ORDERS
  SHOW_INITIAL_ROWS = TRUE;
