-- Runs on a schedule but only consumes warehouse credits when the stream has data.
-- Requires: GRANT EXECUTE TASK ON ACCOUNT TO ROLE <your role>  (run once as ACCOUNTADMIN)
CREATE OR REPLACE TASK {{ DATABASE }}.CORE.TASK_MERGE_ORDERS
  WAREHOUSE = {{ WAREHOUSE }}
  SCHEDULE = '{{ TASK_SCHEDULE }}'
  ALLOW_OVERLAPPING_EXECUTION = FALSE
  WHEN SYSTEM$STREAM_HAS_DATA('{{ DATABASE }}.RAW.ORDERS_STREAM')
AS
  CALL {{ DATABASE }}.CORE.SP_MERGE_ORDERS();

ALTER TASK {{ DATABASE }}.CORE.TASK_MERGE_ORDERS RESUME;
