-- Rollback V007: restore the previous procedure FIRST, then drop the column.
CREATE OR REPLACE PROCEDURE {{ DATABASE }}.CORE.SP_MERGE_ORDERS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  v_started  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
  v_ins      NUMBER DEFAULT 0;
  v_upd      NUMBER DEFAULT 0;
  v_del      NUMBER DEFAULT 0;
  v_has_data BOOLEAN;
BEGIN
  v_has_data := SYSTEM$STREAM_HAS_DATA('{{ DATABASE }}.RAW.ORDERS_STREAM');
  IF (NOT v_has_data) THEN
    RETURN 'no-op: stream empty';
  END IF;

  MERGE INTO {{ DATABASE }}.CORE.ORDERS AS t
  USING (
    SELECT ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_AMOUNT, ORDER_TS, UPDATED_AT,
           METADATA$ACTION AS CDC_ACTION, METADATA$ISUPDATE AS CDC_IS_UPDATE
    FROM {{ DATABASE }}.RAW.ORDERS_STREAM
  ) AS s
  ON t.ORDER_ID = s.ORDER_ID
  WHEN MATCHED AND s.CDC_ACTION = 'DELETE' AND s.CDC_IS_UPDATE = FALSE THEN DELETE
  WHEN MATCHED AND s.CDC_ACTION = 'INSERT' THEN UPDATE SET
       t.CUSTOMER_ID    = s.CUSTOMER_ID,
       t.ORDER_STATUS   = s.ORDER_STATUS,
       t.ORDER_AMOUNT   = s.ORDER_AMOUNT,
       t.ORDER_TS       = s.ORDER_TS,
       t.SRC_UPDATED_AT = s.UPDATED_AT,
       t.DW_UPDATED_AT  = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED AND s.CDC_ACTION = 'INSERT' THEN INSERT
       (ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_AMOUNT, ORDER_TS, SRC_UPDATED_AT)
       VALUES (s.ORDER_ID, s.CUSTOMER_ID, s.ORDER_STATUS, s.ORDER_AMOUNT, s.ORDER_TS, s.UPDATED_AT);

  SELECT "number of rows inserted", "number of rows updated", "number of rows deleted"
    INTO :v_ins, :v_upd, :v_del
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

  INSERT INTO {{ DATABASE }}.AUDIT.PIPELINE_RUN_LOG
    (PIPELINE, STARTED_AT, FINISHED_AT, DURATION_MS, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, STATUS)
  SELECT 'orders_incremental', :v_started, CURRENT_TIMESTAMP(),
         DATEDIFF('millisecond', :v_started, CURRENT_TIMESTAMP()), :v_ins, :v_upd, :v_del, 'SUCCESS';

  RETURN 'inserted=' || v_ins || ' updated=' || v_upd || ' deleted=' || v_del;
EXCEPTION
  WHEN OTHER THEN
    INSERT INTO {{ DATABASE }}.AUDIT.PIPELINE_RUN_LOG
      (PIPELINE, STARTED_AT, FINISHED_AT, STATUS, MESSAGE)
    SELECT 'orders_incremental', :v_started, CURRENT_TIMESTAMP(), 'FAILED', :SQLERRM;
    RAISE;
END;
$$;

ALTER TABLE {{ DATABASE }}.CORE.ORDERS DROP COLUMN IF EXISTS ORDER_CHANNEL;
ALTER TABLE {{ DATABASE }}.RAW.ORDERS  DROP COLUMN IF EXISTS ORDER_CHANNEL;
